version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: studentHub_db
    hostname: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      POSTGRES_USER: studentHub
      POSTGRES_PASSWORD: studentHub#2024
      POSTGRES_DATABASE: studentHub_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: studentHub_db_manager
    environment:
      PGADMIN_DEFAULT_EMAIL: studentHub@gmail.com
      PGADMIN_DEFAULT_PASSWORD: studentHub213
    ports:
      - 5050:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres-data:
  pgadmin-data: