spring:
  datasource:
    url: jdbc:postgresql://ep-rapid-river-a2xclf7m-pooler.eu-central-1.aws.neon.tech/neondb?user=neondb_owner&password=xrYCe90Ksldm&sslmode=require
    username: neondb_owner
    password: xrYCe90Ksldm
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect