spring:
  datasource:
    url: postgresql://neondb_owner:xrYCe90Ksldm@ep-rapid-river-a2xclf7m-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require
    username: studentHub
    password: studentHub#2024
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect